-- ProblemSet 00, November <Date> <Year>
-- Submission by <Your Accenture Email.id> 

1. 

SELECT NAME,salary FROM EMPLOYEE WHERE SALARY >=(SELECT MAX(SALARY) FROM EMPLOYEE where SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE))) ORDER BY SALARY DESC;

TARA CUMMINGS|99475
PAUL WILLS|94791
ADAM WAYNE|94324


 Your Record Count -3
 
 
